# Generated by Django 4.1.7 on 2023-03-27 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('name', models.CharField(max_length=250, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('email', models.EmailField(max_length=250)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household')),
            ],
        ),
    ]
